name: API Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Make wheel package
      run: make wheel
    - name: Install wheel package
      run: pip install dist/*.whl      
    - name: Run commands
      env:
        SIGSCI_EMAIL: ${{ secrets.API_ACCESS_EMAIL }}
        SIGSCI_API_TOKEN: ${{ secrets.API_ACCESS_TOKEN }}
        SIGSCI_CORP: "pxmx"
        SIGSCI_SITE: "pysigsci"
      run: |
        pysigsci --get requests
